### ISSUE TITLE
Target the selector `:host, atom-text-editor` instead of `.editor` for shadow DOM support.

### ISSUE THREAD

**Issue by jacobwgillespie** [olistik/spacegray-base16-ocean-dark#1]
From the Deprecation Cop:

> In index.less: Target the selector `:host, atom-text-editor` instead of `.editor` for shadow DOM support.

**Comment by flynfish** [comment]
:+1: please update!

**Comment by olistik** [comment]
67499c34ffe58023b040976c83e324e8a266b342 should address this issue.
I've published a new version.
