### ISSUE TITLE
Use the `atom-text-editor` tag instead of the `editor` class.

### ISSUE THREAD

**Issue by jacobwgillespie** [olistik/spacegray-base16-ocean-dark#2]
From the Deprecation Cop:

> In index.less: Use the `atom-text-editor` tag instead of the `editor` class.

**Comment by flynfish** [comment]
:+1:

**Comment by olistik** [comment]
67499c34ffe58023b040976c83e324e8a266b342 should address this issue :-)
I've published the new version.
